version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-jessie-node-browsers
    working_directory: ~/php-checklist
    step:
      - checkout
      - run: sudo apt install -y zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: composer install --dev
      - run: composer test
